language: ruby
rvm:
- 2.0.0
- 2.1.2
deploy:
  provider: rubygems
  api_key:
    secure: NoiCCOqmdNpkgefdthA5CeiGz9dAC/YRqUtxXMOr/SMCRZa1zYe6KoYLR133xSWhxQP3dZCRkgVtZtmXYZW6SLk3TT4K1D4bHN51uHabXSq4UVwVsVwF6Bibdgod/iGhEtNyzPFS1sQv+iXEuHUl1Z+/1Zn1qbVDw93Eh6vYghc=
  gem: blinkbox-common_config
  on:
    repo: blinkboxbooks/common_config.rb
    rvm: 2.1.2
    branch: master
