language: ruby
rvm:
- 2.0.0
- 2.1.2
deploy:
  provider: rubygems
  api_key:
    secure: af9asVAbzYzauAetuIneYpv77mjgZ3+93nVQqBTeRaY8JE/QR9xZugfZxsUzO4VCaYMr1tINyFGZOp1YqDO+PhayYkTxcMDO8SVHTskuj5i30v/q7Dx/KYjamd9hFhzXZLapieHsWvfP+HAprm5gbjuiqqOcpqqJcWlYBATtgqo=
  gem: blinkbox-common_config
  on:
    repo: blinkboxbooks/common_config.rb
    rvm: 2.1.2
    branch: master
